# -*- coding: utf-8 -*-
"""project 108.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Unm-brz_SxPzgCb-ESoRVzNs1mhpbvvq
"""

!pip3 install scipy

from google.colab import files
data=files.upload()

import pandas as pd
import csv
import plotly.figure_factory as ff
df=pd.read_csv("project_108.csv")
fig=ff.create_distplot([df["Avg Rating"].tolist()], ["Avg Rating"])
fig.show()